// frameworks/preact-hooks/src/7GUIs-flight-booker/index.jsx
import { render } from "preact";
import { useState } from "preact/hooks";
import { today, validateDate } from "../../../../lib/date";
import { TripType, returnFlight, oneWayFlight } from "./TripType";
import { DateEntry } from "./DateEntry";

const initialDate = today();

function useDate(initialDate) {
	const [date, setDate] = useState(initialDate);
	const [error, setError] = useState(null);

	function updateDate(newDate) {
		setDate(newDate);

		try {
			validateDate(newDate);
			setError(null);
		} catch (error) {
			setError(error.message);
		}
	}

	return [date, error, updateDate];
}

function App() {
	const [tripType, setTripType] = useState(oneWayFlight);
	const [departing, departingError, setDeparting] = useDate(initialDate);
	let [returning, returningError, setReturning] = useDate(initialDate);

	if (
		departingError == null &&
		returningError == null &&
		tripType == returnFlight &&
		returning < departing
	) {
		returningError = "Returning date must be on or after departing date.";
	}

	const isBookDisabled = departingError || returningError;

	function bookFlight() {
		const type = tripType === returnFlight ? "return" : "one-way";

		let message = `You have booked a ${type} flight, departing ${departing}`;
		if (tripType == returnFlight) {
			message += ` and returning ${returning}`;
		}

		alert(message);
	}

	return (
		<>
			<TripType tripType={tripType} setTripType={value => setTripType(value)} />
			<DateEntry
				label="Departing"
				date={departing}
				setDate={newDate => setDeparting(newDate)}
				errorMsg={departingError}
			/>
			<DateEntry
				label="Returning"
				date={returning}
				setDate={newDate => setReturning(newDate)}
				errorMsg={returningError}
				disabled={tripType !== returnFlight}
			/>
			<div class="form-group">
				<button
					disabled={isBookDisabled}
					onClick={bookFlight}
					class="btn btn-primary"
				>
					book
				</button>
			</div>
		</>
	);
}

render(<App />, document.getElementById("app"));

// frameworks/solid-js/src/7GUIs-flight-booker/index.jsx
import { createMemo, createSignal } from "solid-js";
import { render } from "solid-js/web";
import { today, validateDate } from "../../../../lib/date";
import { TripType, RETURN_FLIGHT, ONE_WAY_FLIGHT } from "./TripType";
import { DateEntry } from "./DateEntry";

const initialDate = today();

/**
 * @typedef {import('solid-js').Accessor<T>} Accessor
 * @template T
 */

/**
 * @param {string} initialDate
 * @returns {[Accessor<string>, Accessor<string | null>, (string) => void]}
 */
function useDate(initialDate) {
	const [date, setDate] = createSignal(initialDate);
	const [error, setError] = createSignal(null);

	/** @type {(newDate: string) => void} */
	function updateDate(newDate) {
		setDate(newDate);

		try {
			validateDate(newDate);
			setError(null);
		} catch (error) {
			setError(error.message);
		}
	}

	return [date, error, updateDate];
}

function App() {
	const [tripType, setTripType] = createSignal(ONE_WAY_FLIGHT);
	const [departing, departingError, setDeparting] = useDate(initialDate);
	const [returning, returningError, setReturning] = useDate(initialDate);

	const finalReturningError = createMemo(() => {
		if (
			departingError() == null &&
			returningError() == null &&
			tripType() == RETURN_FLIGHT &&
			returning() < departing()
		) {
			return "Returning date must be on or after departing date.";
		} else {
			return returningError();
		}
	});

	function bookFlight() {
		const type = tripType() === RETURN_FLIGHT ? "return" : "one-way";

		let message = `You have booked a ${type} flight, departing ${departing()}`;
		if (tripType() == RETURN_FLIGHT) {
			message += ` and returning ${returning()}`;
		}

		alert(message);
	}

	return (
		<>
			<TripType
				tripType={tripType()}
				setTripType={value => setTripType(value)}
			/>
			<DateEntry
				label="Departing"
				date={departing()}
				setDate={newDate => setDeparting(newDate)}
				errorMsg={departingError()}
			/>
			<DateEntry
				label="Returning"
				date={returning()}
				setDate={newDate => setReturning(newDate)}
				errorMsg={finalReturningError()}
				disabled={tripType() !== RETURN_FLIGHT}
			/>
			<div class="form-group">
				<button
					disabled={Boolean(departingError() || finalReturningError())}
					onClick={bookFlight}
					class="btn btn-primary"
				>
					book
				</button>
			</div>
		</>
	);
}

render(App, document.getElementById("app"));
