// frameworks/react-hooks/src/7GUIs-flight-booker/DateEntry.jsx
export function DateEntry({
	label,
	date,
	errorMsg,
	setDate,
	disabled = false
}) {
	const inputId = `${label}-date`;
	return (
		<div className={"form-group" + (errorMsg ? " has-error" : "")}>
			<label className="form-label" htmlFor={inputId}>
				{label}
			</label>
			<input
				id={inputId}
				className="form-input"
				type="text"
				value={date}
				onChange={e => setDate(e.target.value)}
				disabled={disabled}
			/>
			{errorMsg && <p className="form-input-hint">{errorMsg}</p>}
		</div>
	);
}

// frameworks/vue/src/7GUIs-flight-booker/DateEntry.vue
<template>
	<div class="form-group" v-bind:class="{ 'has-error': errorMsg }">
		<label class="form-label" v-bind:for="label + '-date'">{{ label }}</label
		><input
			v-bind:id="label + '-date'"
			class="form-input"
			type="text"
			v-bind:value="date"
			v-on:input="e => listeners.setDate(e.target.value)"
			v-bind:disabled="disabled || false"
		/>
		<p v-if="errorMsg" class="form-input-hint">{{ errorMsg }}</p>
	</div>
</template>

<script>
export default {
	props: ["errorMsg", "label", "date", "disabled"]
};
</script>
