// frameworks/solid-js/src/7GUIs-temp-converter/index.jsx
import { createSignal } from "solid-js";
import { render } from "solid-js/web";

function App() {
	const [f, setF] = createSignal(null);
	const [c, setC] = createSignal(null);

	function setBothFromC(value) {
		setC(value);
		setF(+(32 + (9 / 5) * value).toFixed(1));
	}

	function setBothFromF(value) {
		setF(value);
		setC(+((5 / 9) * (value - 32)).toFixed(1));
	}

	return (
		<>
			<input
				value={c()}
				onInput={e => setBothFromC(e.currentTarget.value)}
				type="number"
			/>{" "}
			°c ={" "}
			<input
				value={f()}
				onInput={e => setBothFromF(e.currentTarget.value)}
				type="number"
			/>{" "}
			°f
		</>
	);
}

render(App, document.getElementById("app"));

// frameworks/preact/src/7GUIs-temp-converter/index.jsx
import { render, Component } from "preact";

class App extends Component {
	constructor() {
		super();
		this.state = { c: null, f: null };
	}

	setBothFromC(value) {
		this.setState({
			c: value,
			f: +(32 + (9 / 5) * value).toFixed(1)
		});
	}

	setBothFromF(value) {
		this.setState({
			f: value,
			c: +((5 / 9) * (value - 32)).toFixed(1)
		});
	}

	render(props, state) {
		return (
			<>
				<input
					value={state.c}
					onInput={e => this.setBothFromC(e.currentTarget.value)}
					type="number"
				/>{" "}
				°c ={" "}
				<input
					value={state.f}
					onInput={e => this.setBothFromF(e.currentTarget.value)}
					type="number"
				/>{" "}
				°f
			</>
		);
	}
}

render(<App />, document.getElementById("app"));
