// frameworks/react-hooks/src/7GUIs-flight-booker/TripType.jsx
import React from "react";

export const oneWayFlight = "one-way";
export const returnFlight = "return";

export function TripType({ tripType, setTripType }) {
	return (
		<div className="form-group">
			<label className="form-label" htmlFor="trip-type">
				Trip type
			</label>
			<select
				id="trip-type"
				className="form-select"
				value={tripType}
				onChange={e => setTripType(e.target.value)}
			>
				<option value={oneWayFlight}>one-way flight</option>
				<option value={returnFlight}>return flight</option>
			</select>
		</div>
	);
}

// frameworks/lit-html/src/7GUIs-flight-booker/TripType.js
import { html } from "lit";

export const oneWayFlight = "one-way";
export const returnFlight = "return";

export function TripType(tripType, setTripType) {
	return html`
		<div class="form-group">
			<label class="form-label" for="trip-type">Trip type</label
			><select
				id="trip-type"
				class="form-select"
				value=${tripType}
				@input=${e => setTripType(e.target.value)}
			>
				<option value=${oneWayFlight}>one-way flight</option>
				<option value=${returnFlight}>return flight</option>
			</select>
		</div>
	`;
}
