// frameworks/vue/src/7GUIs-flight-booker/TripType.vue
<template>
	<div class="form-group">
		<label class="form-label" for="trip-type">Trip type</label
		><select
			id="trip-type"
			class="form-select"
			v-on:input="e => listeners.setTripType(e.target.value)"
		>
			<option value="one-way">one-way flight</option>
			<option value="return">return flight</option>
		</select>
	</div>
</template>

<script>
export default {};
</script>

// frameworks/lit-html/src/7GUIs-flight-booker/TripType.js
import { html } from "lit";

export const oneWayFlight = "one-way";
export const returnFlight = "return";

export function TripType(tripType, setTripType) {
	return html`
		<div class="form-group">
			<label class="form-label" for="trip-type">Trip type</label
			><select
				id="trip-type"
				class="form-select"
				value=${tripType}
				@input=${e => setTripType(e.target.value)}
			>
				<option value=${oneWayFlight}>one-way flight</option>
				<option value=${returnFlight}>return flight</option>
			</select>
		</div>
	`;
}
