// frameworks/react-hooks/src/7GUIs-counter/index.jsx
import { useState } from "react";
import ReactDOM from "react-dom";

function App() {
	const [count, setCount] = useState(0);
	return (
		<button
			className="btn badge"
			data-badge={count}
			style={{ marginTop: ".5rem" }}
			onClick={() => setCount(count + 1)}
		>
			count: {count}
		</button>
	);
}

ReactDOM.render(<App />, document.getElementById("app"));

// frameworks/solid-js/src/7GUIs-counter/index.jsx
import { createSignal } from "solid-js";
import { render } from "solid-js/web";

function App() {
	const [count, setCount] = createSignal(0);
	return (
		<button
			class="btn badge"
			data-badge={count()}
			style={{ "margin-top": "0.5rem" }}
			onClick={() => setCount(count() + 1)}
		>
			count: {count()}
		</button>
	);
}

render(App, document.getElementById("app"));
