// frameworks/lit-html/src/7GUIs-temp-converter/index.js
import { html, render } from "lit-html";

const TempConverter = (c, f, setBothFromC, setBothFromF) => html`
	<input .value=${c} @input=${setBothFromC} type="number" />
	°c =
	<input .value=${f} @input=${setBothFromF} type="number" />
	°f
`;

const container = document.getElementById("app");

function update(c, f) {
	/** @param {Event} e */
	function setBothFromC(e) {
		c = e.target.value;
		f = +(32 + (9 / 5) * c).toFixed(1);
		update(c, f);
	}

	/** @param {Event} e */
	function setBothFromF(e) {
		f = e.target.value;
		c = +((5 / 9) * (f - 32)).toFixed(1);
		update(c, f);
	}

	render(TempConverter(c, f, setBothFromC, setBothFromF), container);
}

update("", "");

// frameworks/react-hooks/src/7GUIs-temp-converter/index.js
import React, { useState, Fragment } from "react";
import ReactDOM from "react-dom";

function App() {
	const [f, setF] = useState(null);
	const [c, setC] = useState(null);

	function setBothFromC(value) {
		setC(+value);
		setF(+(32 + (9 / 5) * value).toFixed(1));
	}

	function setBothFromF(value) {
		setF(+value);
		setC(+((5 / 9) * (value - 32)).toFixed(1));
	}

	return (
		<Fragment>
			<input
				value={c}
				onInput={e => setBothFromC(e.target.value)}
				type="number"
			/>{" "}
			°c ={" "}
			<input
				value={f}
				onInput={e => setBothFromF(e.target.value)}
				type="number"
			/>{" "}
			°f
		</Fragment>
	);
}

ReactDOM.render(<App />, document.getElementById("app"));
