// frameworks/react-hooks/src/7GUIs-timer/index.js
import React, { useEffect, useState, Fragment } from "react";
import ReactDOM from "react-dom";

function App() {
	const [lastRenderTime, setLastRenderTime] = useState(performance.now());
	const [elapsed, setElapsed] = useState(0);
	const [duration, setDuration] = useState(5000);

	useEffect(() => {
		if (elapsed < duration) {
			const now = performance.now();
			const timeToAdd = Math.min(now - lastRenderTime, duration - elapsed);
			setElapsed(prevElapsed => prevElapsed + timeToAdd);
			setLastRenderTime(now);
		}
	}, [elapsed, duration, lastRenderTime]);

	return (
		<Fragment>
			<label>
				Elapsed time: <progress value={elapsed / duration} />
			</label>
			<div>{(elapsed / 1000).toFixed(1)}s</div>
			<label>
				Duration:{" "}
				<input
					type="range"
					min="1"
					max="20000"
					value={duration}
					onInput={e => setDuration(e.target.value)}
				/>
			</label>
			<div>
				<button
					className="btn btn-primary"
					onClick={() => {
						setElapsed(0);
						setLastRenderTime(performance.now());
					}}
				>
					Reset
				</button>
			</div>
		</Fragment>
	);
}

ReactDOM.render(<App />, document.getElementById("app"));

// frameworks/lit-html/src/7GUIs-timer/index.js
import { html, render } from "lit";

const Timer = (elapsed, duration, setDuration, reset) => html`
	<label>
		Elapsed time: <progress value=${elapsed / duration}></progress
	></label>
	<div class="elapsed">${(elapsed / 1000).toFixed(1)}s</div>
	<label>
		Duration:
		<input
			type="range"
			min="1"
			max="20000"
			.value=${duration}
			@input=${setDuration}
		/>
	</label>
	<div>
		<button class="btn btn-primary" @click=${reset}>Reset</button>
	</div>
`;

const container = document.getElementById("app");

function update(elapsed, duration, last_time) {
	const reset = () => update(0, duration, performance.now());
	const setDuration = e => update(elapsed, e.target.value, last_time);

	if (elapsed < duration) {
		requestAnimationFrame(time =>
			update(
				elapsed + Math.min(time - last_time, duration - elapsed),
				duration,
				time
			)
		);
	}

	render(Timer(elapsed, duration, setDuration, reset), container);
}

update(0, 5000, performance.now());
