// frameworks/preact-signals/src/7GUIs-counter/index.jsx
import { signal } from "@preact/signals";
import { render } from "preact";
import { createModel, useModel } from "../../../../lib/model/createModel.js";

const Counter = createModel(() => {
	const count = signal(0);
	const increment = () => {
		count.value += 1;
	};

	return {
		count,
		increment
	};
});

function App() {
	const model = useModel(Counter);

	return (
		<button
			class="btn badge"
			data-badge={model.count}
			style="margin-top: .5rem"
			onClick={() => model.increment()}
		>
			count: {model.count}
		</button>
	);
}

render(<App />, document.getElementById("app"));

// frameworks/lit-html/src/7GUIs-counter/index.js
import { html, render } from "lit";

const Counter = (count, increment) => html`
	<button
		class="btn badge"
		data-badge=${count}
		style="margin-top: 0.5rem;"
		@click=${increment}
	>
		count: ${count}
	</button>
`;

const container = document.getElementById("app");

function update(count) {
	const increment = () => update(count + 1);
	render(Counter(count, increment), container);
}

update(0);
