// frameworks/preact-hooks/src/7GUIs-counter/index.jsx
import { render } from "preact";
import { useState } from "preact/hooks";

function App() {
	const [count, setCount] = useState(0);
	return (
		<button
			class="btn badge"
			data-badge={count}
			style="margin-top: .5rem"
			onClick={() => setCount(count + 1)}
		>
			count: {count}
		</button>
	);
}

render(<App />, document.getElementById("app"));

// frameworks/lit-html/src/7GUIs-counter/index.js
import { html, render } from "lit";

const Counter = (count, increment) => html`
	<button
		class="btn badge"
		data-badge=${count}
		style="margin-top: 0.5rem;"
		@click=${increment}
	>
		count: ${count}
	</button>
`;

const container = document.getElementById("app");

function update(count) {
	const increment = () => update(count + 1);
	render(Counter(count, increment), container);
}

update(0);
